### ISSUE TITLE
launcher doesn't default to default URL correctly

### ISSUE THREAD

**Issue by justnoise** [elotl/itzo-launcher#1]
If the file doesn't exist there is an error but we still try to read the contents of the file.  I think there is an errant `!` in front of the `os.IsNotExist`. This also affects the checking of the version file as well.  The version might not be specified in some setups (it isn't required) so this could break some setups.

https://github.com/elotl/itzo-launcher/blob/85facef5370e1738203d898762459a782a972b8a/cmd/itzo-launcher/itzo-launcher.go#L55-L60

**Comment by ldx** [comment]
Fixed in #2
